### PR TITLE
Support MySQL 5.7

### LINKED ISSUE #12: Compilation issue with MySQL-5.7 sources
[ 10%] Building CXX object storage/q4m/CMakeFiles/queue.dir/src/ha_queue.cc.o
/usr/src/mysql/mysql-5.7/storage/q4m/src/ha_queue.cc:43:22: fatal error: sql_priv.h: No such file or directory
compilation terminated.
storage/q4m/CMakeFiles/queue.dir/build.make:86: recipe for target 'storage/q4m/CMakeFiles/queue.dir/src/ha_queue.cc.o' failed
make[2]: *** [storage/q4m/CMakeFiles/queue.dir/src/ha_queue.cc.o] Error 1
CMakeFiles/Makefile2:748: recipe for target 'storage/q4m/CMakeFiles/queue.dir/all' failed
make[1]: *** [storage/q4m/CMakeFiles/queue.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
root@cloud:/usr/src/mysql/mysql-5.7#

### PR DESCRIPTION
**Pull request by hirose31**
Support MySQL 5.7.

I've tested with `run_tests.pl` on both MySQL 5.7.24 and 5.6.43.

resolve #12

### CODE REVIEW

**Comment by MartinK63** [comment]
I can confirm that the patches work with MySQL 5.7.25 on a ubuntu 18.04 LTS.
Test with run_tests OK but fails with BIG_TESTS="1" 
#   Failed test at t/10-largedata.t line 34.
DBD::mysql::db do failed: MySQL server has gone away at t/10-largedata.t line 34
My last test was with 5.1 and test worked even with BIG_TESTS
I don't know what that means...

**Comment by hirose31** [comment]
All tests are OK on my environment (MySQL 5.7.24 on Ubuntu 18.04).

```
u182[mysql-5.7)~/LOCAL/q4m]$ BIG_TESTS=1 MYSQL_DB=t DBI_USER=root DBI_PASSWORD=blah DBI='dbi:mysql:database=t;host=127.0.0.1;port=3306' ./run_tests.pl
t/01-base-rnd_pos.t ....................... ok
(snip)
t/09-pqueue-single-table.t ................ ok
t/10-largedata.t .......................... ok
t/11-conc-compact-w-insert.t .............. ok
(snip)
All tests successful.
Files=26, Tests=87955, 522 wallclock secs (10.20 usr  2.10 sys + 57.85 cusr 15.98 csys = 86.13 CPU)
Result: PASS
```

**Comment by MartinK63** [comment]
Increasing the 
max_allowed_packet=16M
in the servers config file did the trick

**Comment by MartinK63** [comment]
On a 4GB Linode latest Ubuntu 18.04 (4.15.0-45-generic x86_64):
All tests successful.
Files=26, Tests=87647, 233 wallclock secs (10.27 usr  0.92 sys + 61.74 cusr 10.43 csys = 83.36 CPU)
Result: PASS
On a 8GB local virtual machine latest Ubuntu 18.04 (4.15.0-45-generic x86_64):
All tests successful.
Files=26, Tests=87716, 367 wallclock secs ( 5.00 usr  6.47 sys + 22.15 cusr 42.36 csys = 75.98 CPU)
Result: PASS

**Comment by azrle** [comment]
@kazuho It has been a while. We would be grateful if you could check this PR.
